-- Icons that are used in other plugins
return {
  kind = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = "󰉋 ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = "󰟢 ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  telescope = {
    Forward = "  ",
    Code = "   ",
    Reference = "   ",
    Type = "   ",
    FindFile = " 󰱼  ",
    Search = "   ",
    FindText = " 󰊄  ",
    Implementation = "   ",
    Symbols = "   ",
  },
  git = {

    LineAdded = " ",
    LineModified = " ",
    LineRemoved = " ",
    FileDeleted = "",
    FileIgnored = "◌",
    FileRenamed = "󱞩",
    FileStaged = "✓",
    FileUnmerged = "",
    -- FileUnstaged = "*",
    FileUnstaged = "",
    FileUntracked = "?",
    Repo = " ",
    Branch = "",
  },
  ui = {
    ArrowCircleDown = "",
    ArrowCircleLeft = "",
    ArrowCircleRight = "",
    ArrowCircleUp = "",
    BoldArrowDown = "",
    BoldArrowLeft = "",
    BoldArrowRight = "",
    BoldArrowUp = "",
    BoldClose = "",
    BoldDividerLeft = "",
    BoldDividerRight = "",
    BoldLineLeft = "▎",
    BookMark = "",

    Check = "",

    ChevronDown = "",
    ChevronLeft = "",
    ChevronRight = "",
    ChevronUp = "",
    Close = "󰅖",
    DividerLeft = "",
    DividerRight = "",
    DoubleChevronRight = "»",
    Ellipsis = "",
    EmptyFolder = "",
    EmptyFolderOpen = "",
    File = "",
    FileSymlink = "",
    Files = " ",

    Folder = "󰉋",
    FolderOpen = "",
    FolderSymlink = "",
    Gear = " ",
    History = " ",
    LineLeft = "▏",
    LineMiddle = "│",
    NewFile = " ",
    Package = " ",
    Pencil = "󰏫 ",
    Project = " ",
    Search = " ",
    SignIn = " ",
    SignOut = " ",
    Text = " ",
    Triangle = "󰐊",
    -- TriangleShortArrowDown = "",
    -- TriangleShortArrowLeft = "",
    -- TriangleShortArrowRight = "",
    -- TriangleShortArrowUp = "",
    TriangleArrowDown = "",
    TriangleArrowLeft = "",
    TriangleArrowRight = "",
    TriangleArrowUp = "",
  },
  diagnostics = {
    BoldError = "",
    BoldWarning = "",
    BoldInformation = "",
    BoldQuestion = "",
    BoldHint = "󰌵",
    -- Error = "",
    -- Warning = "",
    -- Information = "",
    -- Question = "",
    -- Hint = "󰌶",
    Debug = "",
    Trace = "✎",
  },
  misc = {

    Smiley = "",
    Package = "",
  },
  NotUsed = {
    -- Not used, but may be useful in the future

    -- LineAdded = " ",
    -- LineModified = " ",
    -- LineRemoved = " ",
    -- FileDeleted = " ",
    -- FileRenamed = " ",
    -- FileStaged = "󰄴",
    -- FileUntracked = "",

    -- BoxChecked = "",
    -- Bug = " ",
    -- Stacks = "",
    -- Scopes = "",
    -- Watches = "󰂥",
    -- DebugConsole = "",
    -- Calendar = "",
    -- Circle = " ",
    -- CloudDownload = " ",
    -- Comment = "",
    -- Dashboard = "",
    -- Lightbulb = " ",
    -- List = " ",
    -- Lock = " ",
    -- Note = " ",
    -- Plus = " ",
    -- SymlinkArrow = " ➛ ",
    -- Tab = "󰌒 ",
    -- Table = " ",
    -- Target = "󰀘 ",
    -- Telescope = " ",
    -- Tree = "",

    -- Diff = " ",

    -- CircuitBoard = "",
    -- Robot = "󰚩 ",
    -- Squirrel = "",
    -- Tag = "",
    -- Watch = "",
  },
}
